import {
  UserProfile,
  FreelancerProfile,
  FreelanceJob,
  ComActProject,
  Startup,
  Challenge,
  ResourceExchangeItem,
  Course,
  Proposal,
  ImpactLedgerEntry,
} from '../types';

export const INITIAL_PROFILE: UserProfile = {
  id: 'usr-current',
  name: 'Nga Nguyen',
  email: 'nga.nguyen@etopia.org',
  role: 'innovator',
  impactScore: 920,
  reputationPoints: 1850,
  trustScore: 98,
  xp: 4850,
  skills: ['React', 'TypeScript', 'Gemini API', 'Sustainable Tech', 'Startup Growth', 'UI/UX Design'],
  bio: 'Platform Innovator and software architect. Dedicated to design-driven civic helpers, sustainable startup models, and decentralized social networks.',
  avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=200',
  badges: [
    {
      id: 'bdg-foundation',
      name: 'Digital Pioneer',
      description: 'Completed basic digital literacy training onboarding on eTopia.',
      icon: 'Monitor',
      rarity: 'common',
    },
    {
      id: 'bdg-climate',
      name: 'Green Citizen',
      description: 'Joined and completed 3 environmental restoration missions.',
      icon: 'Leaf',
      rarity: 'rare',
    },
    {
      id: 'bdg-civic',
      name: 'Civic Pillar',
      description: 'Acquired 100% voting turnout on public governance proposals.',
      icon: 'Vote',
      rarity: 'epic',
    },
  ],
};

export const INITIAL_FREELANCERS: FreelancerProfile[] = [
  {
    id: 'fl-1',
    name: 'Siddharth Mehta',
    title: 'Senior Machine Learning Engineer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
    skills: ['NLP', 'Python', 'Gemini API', 'Scikit-Learn', 'TensorFlow'],
    hourlyRate: 85,
    verified: true,
    rating: 4.9,
    completedJobsCount: 42,
    reputationPoints: 850,
    portfolio: [
      { id: 'p-1-1', title: 'Sentiment Analyzer for Civic Forums', description: 'Classifies local grievances over 12 sectors with 94% accuracy.' },
    ],
  },
  {
    id: 'fl-2',
    name: 'Maria Dupont',
    title: 'Interaction & Accessibility Designer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
    skills: ['Figma', 'WCAG 2.2 AA', 'TailwindCSS', 'React', 'Prototyping'],
    hourlyRate: 65,
    verified: true,
    rating: 4.8,
    completedJobsCount: 28,
    reputationPoints: 620,
    portfolio: [
      { id: 'p-2-1', title: 'Inclusive Banking Web App', description: 'A completely screen-readable UI optimized for visual impairments.' },
    ],
  },
  {
    id: 'fl-3',
    name: 'Kenji Sato',
    title: 'Data Analyst & Visualization Expert',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150',
    skills: ['D3.js', 'SQL', 'Python', 'Tableau', 'Social Impact Auditing'],
    hourlyRate: 70,
    verified: false,
    rating: 4.7,
    completedJobsCount: 15,
    reputationPoints: 340,
    portfolio: [
      { id: 'p-3-1', title: 'Carbon Footprint Registry dashboard', description: 'Visualizes corporate scope 1-3 carbon records over geographic districts.' },
    ],
  },
];

export const INITIAL_JOBS: FreelanceJob[] = [
  {
    id: 'job-1',
    title: 'AI Grievance Classifier for Rural District',
    description: 'We need an experienced NLP engineer to build an ingestion script that routes community complaints into respective emergency and sanitation queues automatically.',
    category: 'AI',
    budget: 3500,
    skillsRequired: ['Python', 'NLP', 'Gemini API', 'Prompt Engineering'],
    postedBy: 'UNDP Regional Initiative',
    status: 'open',
    proposalsCount: 9,
  },
  {
    id: 'job-2',
    title: 'WCAG 2.2 Remediation for Literacy Platform',
    description: 'Optimize our microlearning courses with completely voice-navigable elements, screen-reader focus hierarchies, and high-contrast styling guides.',
    category: 'UX/UI',
    budget: 1800,
    skillsRequired: ['WCAG 2.2 AA', 'Accessibility', 'React', 'TailwindCSS'],
    postedBy: 'eTopia Academy Admin',
    status: 'open',
    proposalsCount: 5,
  },
  {
    id: 'job-3',
    title: 'Predictive Modeling for Cooperative Agriculture Yields',
    description: 'Build a light Scikit-Learn pipeline to ingest historical rainfall records and predict next-quarter sorghum seed distributions for 12 local villages.',
    category: 'Data Science',
    budget: 4200,
    skillsRequired: ['Python', 'Scikit-Learn', 'Data Science', 'Agriculture'],
    postedBy: 'AgriCoop South',
    status: 'open',
    proposalsCount: 14,
  },
];

export const INITIAL_PROJECTS: ComActProject[] = [
  {
    id: 'proj-1',
    title: 'District Digital Inclusion Portal Development',
    description: 'Large-scale collaborative build for establishing visual, offline-first kiosks supporting civic filings and digital certificates throughout northern clinics.',
    postedBy: 'org-muni-north',
    orgName: 'Municipal Informatics Unit',
    budget: 15000,
    deadline: '2026-09-30',
    status: 'team_formation',
    requiredTeamSize: 4,
    joinedTeamMembers: ['Alex Rivera', 'Maria Dupont'],
    deliverables: [
      { id: 'del-1-1', title: 'Offline sync architecture design doc', description: 'System design layout', status: 'approved' },
      { id: 'del-1-2', title: 'Vandalism-proof kiosk touchscreen UI spec', description: 'User interface specifications', status: 'pending' },
      { id: 'del-1-3', title: 'District local node backend deployment', description: 'Dockerized server instances', status: 'pending' },
    ],
    integrationWebhookSimulated: true,
  },
  {
    id: 'proj-2',
    title: 'Circular Waste Management Routing Optimization',
    description: 'Develop a smart collection scheduler integrating container fill status reports from municipal sensors with localized waste collectors to save carbon emission routing.',
    postedBy: 'org-green-circle',
    orgName: 'GreenCircle Alliance',
    budget: 22000,
    deadline: '2026-11-15',
    status: 'planning',
    requiredTeamSize: 5,
    joinedTeamMembers: ['Kenji Sato'],
    deliverables: [
      { id: 'del-2-1', title: 'Sensor API telemetry mock wrapper', description: 'Wrapper code to match simulator streams', status: 'pending' },
      { id: 'del-2-2', title: 'Routing dashboard visual map', description: 'SVG canvas route maps', status: 'pending' },
    ],
    integrationWebhookSimulated: false,
  },
];

export const INITIAL_STARTUPS: Startup[] = [
  {
    id: 'sup-1',
    name: 'SoliShare Energy',
    oneLiner: 'De-centralized solar micro-grids matching local power abundance to grid-isolated homes.',
    description: 'SoliShare automates energy transactions between neighborhood batteries utilizing lightweight peer brokers. Households with extra solar sell cheap units to next-door energy-poor dwellings, generating local returns.',
    founders: ['Zoe Vance', 'Marcus Vance'],
    sector: 'CleanTech',
    stage: 'seed',
    startupScore: 88,
    fundingGoal: 120000,
    raisedAmount: 78500,
    pitchCompetitionParticipant: true,
    needsMentorship: true,
  },
  {
    id: 'sup-2',
    name: 'ScribeRx Health',
    oneLiner: 'Speech-to-prescription voice assistant translating oral consults into regional languages.',
    description: 'ScribeRx listens during village wellness sessions and automatically structures prescriptions into 6 domestic oral dialects, generating audio guides for illiterate medication consumers to foster critical health adherence.',
    founders: ['Dr. Amina El-Amin'],
    sector: 'MedTech / Inclusion',
    stage: 'pre-seed',
    startupScore: 94,
    fundingGoal: 50000,
    raisedAmount: 12000,
    pitchCompetitionParticipant: true,
    needsMentorship: true,
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'crs-1',
    title: 'Intro to Ethical Generative AI Application Build',
    description: 'Learn to leverage large language models responsibly, designing bias defense frameworks, and auditing generative endpoints to build safe civic helpers.',
    instructorName: 'Sarah Jenkins, Lead AI Ethicist',
    xpWorth: 250,
    level: 'Beginner',
    enrolledCount: 412,
    chapters: [
      'Welcome to Generative Governance',
      'Prompt Design for Bias Defense & Accuracy',
      'Validating Model Responses with Strict Schemas',
      'Deploying an Inclusive AI Grounded Assistant',
    ],
    badgeGiven: 'bdg-foundation',
  },
  {
    id: 'crs-2',
    title: 'Circular Economics & Environmental Stewardship',
    description: 'Master the core mechanics of localized supply lines, zero-waste micro-business setup, carbon estimation auditing, and sustainable development modeling.',
    instructorName: 'Prof. David Okoye',
    xpWorth: 400,
    level: 'Intermediate',
    enrolledCount: 189,
    chapters: [
      'The Linear vs Circular Economy Paradigm',
      'Mapping Local Resource Streams manually & digitally',
      'Auditing Upstream Carbon in Micro-production',
      'Constructing Net-Positive Local Enterprises',
    ],
    badgeGiven: 'bdg-climate',
  },
];

export const INITIAL_CHALLENGES: Challenge[] = [
  {
    id: 'ch-1',
    title: 'Eradicating Urban Digital Deserts',
    description: 'Creating affordable, self-sustaining mesh internet grids inside inner-city low-income sectors to allow zero-cost learning and civic platform access.',
    category: 'Digital Inclusion',
    sdg: 9, // Industry, Innovation and Infrastructure
    postedBy: 'Global Education Council',
    status: 'volunteers_joining',
    volunteersNeeded: 15,
    volunteersJoined: 8,
    fundingGoal: 8500,
    fundingRaised: 4200,
    impactMetrics: 'Targeting 2,500 active youth lines setup',
  },
  {
    id: 'ch-2',
    title: 'Combating Extreme Climate Heat Waves',
    description: 'Rapid orchestration of community-designed rooftop gardens and reflective paint treatments to mitigate thermal heat trap effects in high-density informal neighborhoods.',
    category: 'Climate Change',
    sdg: 13, // Climate Action
    postedBy: 'Habitat & Resilience Network',
    status: 'community_formulating',
    volunteersNeeded: 45,
    volunteersJoined: 12,
    fundingGoal: 15000,
    fundingRaised: 3000,
    impactMetrics: 'Goal: reduce interior room temperatures by up to 4°C',
  },
];

export const INITIAL_RESOURCE_ITEMS: ResourceExchangeItem[] = [
  {
    id: 'res-1',
    type: 'grant',
    title: 'Government Social Innovation Fund 2026',
    description: 'Direct capital distribution of up to $20k for initiatives implementing local, verifiable digital participation structures in subregions.',
    provider: 'Department of Digital Governance',
    valueAmount: 20000,
    status: 'available',
  },
  {
    id: 'res-2',
    type: 'sponsorship',
    title: 'TechGiant Cloud Ingress Infrastructure Credits',
    description: 'Provision of up to $5,000 in servers, storage nodes, and premium APIs for green clean-tech startups.',
    provider: 'TechGiant Philanthropies',
    valueAmount: 5000,
    status: 'matched',
    recipientProject: 'SoliShare Energy',
    matchedDate: '2026-04-12',
  },
  {
    id: 'res-3',
    type: 'donation',
    title: 'Critical Hardware Equipment (Tablet Recovers)',
    description: 'Batch of 50 refurbished touch tablets with solar charger backpacks for distributing to rural educational coordinators.',
    provider: 'Retail Logistics Solidarities',
    valueAmount: 3500,
    status: 'available',
  },
];

export const INITIAL_PROPOSALS: Proposal[] = [
  {
    id: 'prop-1',
    title: 'Distribute 30% of Community Reserves to Startup ScribeRx',
    description: 'Allocating $10,000 from the eTopia common impact vault to subsidize active clinical deployment of audio prescription translations in rural regional clinics.',
    proposer: 'Sarah Jenkins',
    proposerRole: 'community_admin',
    votesFor: 1840,
    votesAgainst: 120,
    status: 'active',
    fundRequested: 10000,
    endsAt: '2026-06-25',
  },
  {
    id: 'prop-2',
    title: 'Standardize Universal Transparency Web3 Hash Ledger for Grants',
    description: 'Proposal to bind all future NGO fund deposits with automatic blockchain status receipts to enforce extreme, immutable financial accountability.',
    proposer: 'Kenji Sato',
    proposerRole: 'member',
    votesFor: 920,
    votesAgainst: 810,
    status: 'active',
    endsAt: '2026-06-18',
  },
];

export const INITIAL_LEDGER_ENTRIES: ImpactLedgerEntry[] = [
  {
    id: 'led-1',
    type: 'donation_utilized',
    title: 'SoliShare Grid Phase-1 hardware Purchase',
    description: 'Utilized corporate sponsorship to acquire 16 lithium cells deployed to District A battery rigs.',
    amountText: '$4,150.00 USD',
    date: '2026-05-18',
    transparencyHash: '0x8f2d5e9b7a4c1065e8aef1c24bd90e78',
  },
  {
    id: 'led-2',
    type: 'volunteer_hours_recorded',
    title: 'Community Heat Garden Sourcing',
    description: 'Registered 32 verified labor contributions towards soil potting and plant layout work on high school roofs.',
    amountText: '32 Hours',
    date: '2026-05-24',
    transparencyHash: '0x3a4b7c1e9f0d2c8e7a6d5b4c301e29fa',
  },
  {
    id: 'led-3',
    type: 'education_certified',
    title: 'Generative AI Ethics Badges Issued',
    description: 'Disbursed certifications to 12 members who successfully cleared the final model-bias auditing lab.',
    amountText: '12 Certifications',
    date: '2026-05-28',
    transparencyHash: '0xf8e7d6c5b4a3928170615243322110df',
  },
];
